version: '3.7'

services:
  db:
    image: postgres:10-alpine
    container_name: kidslike-db
    restart: on-failure
    init: true
    ports:
      - 5429:5432
    environment:
      POSTGRES_USER: kidslike
      POSTGRES_PASSWORD: qwerty
      POSTGRES_MULTIPLE_DATABASES: kidslike
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kidslike']
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s
